### ISSUE TITLE
zigbee2mqtt

### ISSUE THREAD

**Issue by pexcn** [pexcn/docker-images#16]
docker-compose.yml
```yml
version: '3.9'

services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:1.24.0
    container_name: zigbee2mqtt
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: Asia/Taipei
    devices:
      - /dev/ttyACM0
    volumes:
      - ./zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
```
