### ISSUE TITLE
use docker secret

### ISSUE THREAD

**Issue by pexcn** [pexcn/docker-images#21]
like:
```yml
# ...
    environment:
      GF_SECURITY_ADMIN_PASSWORD__FILE: /run/secrets/passwd_file
    secrets:
      - source: admin_password
        target: passwd_file

secrets:
  admin_password:
    file: ./test
```
